// packages/react-mui/src/components/TaskTable.tsx
import { useState } from 'react'
import {
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TableSortLabel,
  Chip,
} from '@mui/material'
import type { Task, TaskStatus, TaskPriority } from '../types/task'

type Order = 'asc' | 'desc'
type SortableColumn = keyof Task

type ChipColor = 'default' | 'primary' | 'secondary' | 'error' | 'info' | 'success' | 'warning'

const STATUS_META: Record<TaskStatus, { label: string; color: ChipColor }> = {
  pending: { label: '未処理', color: 'default' },
  in_review: { label: '審査中', color: 'primary' },
  approved: { label: '承認済み', color: 'success' },
  rejected: { label: '差戻し', color: 'error' },
  on_hold: { label: '保留中', color: 'warning' },
}

const PRIORITY_META: Record<TaskPriority, { label: string; color: ChipColor }> = {
  high: { label: '高', color: 'error' },
  medium: { label: '中', color: 'warning' },
  low: { label: '低', color: 'default' },
}

function sortTasks(tasks: Task[], orderBy: SortableColumn, order: Order): Task[] {
  return [...tasks].sort((a, b) => {
    const av = String(a[orderBy] ?? '')
    const bv = String(b[orderBy] ?? '')
    const cmp = av.localeCompare(bv, 'ja')
    return order === 'asc' ? cmp : -cmp
  })
}

interface Column {
  id: SortableColumn
  label: string
  width?: number | string
}

const COLUMNS: Column[] = [
  { id: 'title', label: 'タスク名' },
  { id: 'type', label: '申請種別', width: 120 },
  { id: 'status', label: 'ステータス', width: 110 },
  { id: 'priority', label: '優先度', width: 80 },
  { id: 'dueDate', label: '期限', width: 110 },
  { id: 'requester', label: '申請者', width: 130 },
]

interface TaskTableProps {
  tasks: Task[]
}

export function TaskTable({ tasks }: TaskTableProps) {
  const [order, setOrder] = useState<Order>('asc')
  const [orderBy, setOrderBy] = useState<SortableColumn>('dueDate')

  function handleSort(column: SortableColumn) {
    if (orderBy === column) {
      setOrder((prev) => (prev === 'asc' ? 'desc' : 'asc'))
    } else {
      setOrderBy(column)
      setOrder('asc')
    }
  }

  const sorted = sortTasks(tasks, orderBy, order)

  return (
    <Paper
      sx={{
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
      }}
    >
      <TableContainer sx={{ flexGrow: 1, overflow: 'auto' }}>
        <Table stickyHeader size="small" aria-label="タスク一覧">
          <TableHead>
            <TableRow>
              {COLUMNS.map((col) => (
                <TableCell
                  key={col.id}
                  width={col.width}
                  sortDirection={orderBy === col.id ? order : false}
                >
                  <TableSortLabel
                    active={orderBy === col.id}
                    direction={orderBy === col.id ? order : 'asc'}
                    onClick={() => handleSort(col.id)}
                  >
                    {col.label}
                  </TableSortLabel>
                </TableCell>
              ))}
            </TableRow>
          </TableHead>
          <TableBody>
            {sorted.map((task) => (
              <TableRow
                key={task.id}
                hover
                sx={{ cursor: 'default' }}
              >
                <TableCell>{task.title}</TableCell>
                <TableCell>{task.type}</TableCell>
                <TableCell>
                  <Chip
                    label={STATUS_META[task.status].label}
                    color={STATUS_META[task.status].color}
                    size="small"
                    variant="filled"
                  />
                </TableCell>
                <TableCell>
                  <Chip
                    label={PRIORITY_META[task.priority].label}
                    color={PRIORITY_META[task.priority].color}
                    size="small"
                    variant="outlined"
                  />
                </TableCell>
                <TableCell>{task.dueDate}</TableCell>
                <TableCell>{task.requester}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
    </Paper>
  )
}

// packages/angular-material/src/app/task-table/task-table.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core'
import { MatTableModule } from '@angular/material/table'
import { MatSortModule, Sort } from '@angular/material/sort'
import { MatChipsModule } from '@angular/material/chips'
import type { Task, TaskStatus, TaskPriority } from '../task.model'

interface StatusMeta {
  label: string
  cssClass: string
}

interface PriorityMeta {
  label: string
  cssClass: string
}

const STATUS_META: Record<TaskStatus, StatusMeta> = {
  pending: { label: '未処理', cssClass: 'chip-pending' },
  in_review: { label: '審査中', cssClass: 'chip-in-review' },
  approved: { label: '承認済み', cssClass: 'chip-approved' },
  rejected: { label: '差戻し', cssClass: 'chip-rejected' },
  on_hold: { label: '保留中', cssClass: 'chip-on-hold' },
}

const PRIORITY_META: Record<TaskPriority, PriorityMeta> = {
  high: { label: '高', cssClass: 'chip-high' },
  medium: { label: '中', cssClass: 'chip-medium' },
  low: { label: '低', cssClass: 'chip-low' },
}

@Component({
  selector: 'app-task-table',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MatTableModule, MatSortModule, MatChipsModule],
  template: `
    <div class="table-wrapper">
      <table mat-table [dataSource]="tasks()" matSort (matSortChange)="sortChange.emit($event)" class="mat-elevation-z1">
        <ng-container matColumnDef="title">
          <th mat-header-cell *matHeaderCellDef mat-sort-header>タスク名</th>
          <td mat-cell *matCellDef="let task">{{ task.title }}</td>
        </ng-container>

        <ng-container matColumnDef="type">
          <th mat-header-cell *matHeaderCellDef mat-sort-header>申請種別</th>
          <td mat-cell *matCellDef="let task">{{ task.type }}</td>
        </ng-container>

        <ng-container matColumnDef="status">
          <th mat-header-cell *matHeaderCellDef mat-sort-header>ステータス</th>
          <td mat-cell *matCellDef="let task">
            <mat-chip-set>
              <mat-chip [class]="statusMeta(task.status).cssClass" disableRipple>
                {{ statusMeta(task.status).label }}
              </mat-chip>
            </mat-chip-set>
          </td>
        </ng-container>

        <ng-container matColumnDef="priority">
          <th mat-header-cell *matHeaderCellDef mat-sort-header>優先度</th>
          <td mat-cell *matCellDef="let task">
            <mat-chip-set>
              <mat-chip [class]="priorityMeta(task.priority).cssClass" disableRipple>
                {{ priorityMeta(task.priority).label }}
              </mat-chip>
            </mat-chip-set>
          </td>
        </ng-container>

        <ng-container matColumnDef="dueDate">
          <th mat-header-cell *matHeaderCellDef mat-sort-header>期限</th>
          <td mat-cell *matCellDef="let task">{{ task.dueDate }}</td>
        </ng-container>

        <ng-container matColumnDef="requester">
          <th mat-header-cell *matHeaderCellDef mat-sort-header>申請者</th>
          <td mat-cell *matCellDef="let task">{{ task.requester }}</td>
        </ng-container>

        <tr mat-header-row *matHeaderRowDef="displayedColumns; sticky: true"></tr>
        <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>

        <tr class="mat-row" *matNoDataRow>
          <td class="mat-cell no-data-cell" [attr.colspan]="displayedColumns.length">
            該当するタスクがありません
          </td>
        </tr>
      </table>
    </div>
  `,
  styles: `
    :host {
      display: block;
      height: 100%;
    }
    .table-wrapper {
      height: 100%;
      overflow: auto;
    }
    table {
      width: 100%;
    }
    .no-data-cell {
      padding: 24px;
      text-align: center;
      color: var(--mat-sys-on-surface-variant);
    }
    .chip-pending { background-color: var(--mat-sys-surface-variant) !important; }
    .chip-in-review { background-color: #e3f2fd !important; color: #1565c0 !important; }
    .chip-approved { background-color: #e8f5e9 !important; color: #2e7d32 !important; }
    .chip-rejected { background-color: #fce4ec !important; color: #c62828 !important; }
    .chip-on-hold { background-color: #fff8e1 !important; color: #f57f17 !important; }
    .chip-high { background-color: #fce4ec !important; color: #c62828 !important; }
    .chip-medium { background-color: #fff3e0 !important; color: #e65100 !important; }
    .chip-low { background-color: var(--mat-sys-surface-variant) !important; }
  `,
})
export class TaskTableComponent {
  readonly tasks = input.required<Task[]>()
  readonly sortChange = output<Sort>()

  readonly displayedColumns = ['title', 'type', 'status', 'priority', 'dueDate', 'requester']

  statusMeta(status: TaskStatus): StatusMeta {
    return STATUS_META[status]
  }

  priorityMeta(priority: TaskPriority): PriorityMeta {
    return PRIORITY_META[priority]
  }
}
